### ISSUE TITLE
Cannot execute solution binary on linux

### ISSUE THREAD

**Issue by ljden** [DanSpicyTaco/MTRN4110_PhaseB_Marking#2]
Running `./sln` returns the following error:
> bash: ./sln: cannot execute binary file: Exec format error

OS: Ubuntu 18.04

**Comment by DanSpicyTaco** [comment]
I'll try creating a new binary compiled on the CSE machines - hopefully that will work :)

**Comment by DanSpicyTaco** [comment]
Recompiled and successfully tested on CSE machine.
