### ISSUE TITLE
Can't account for a double turn

### ISSUE THREAD

**Issue by AlyVirani** [DanSpicyTaco/MTRN4110_PhaseB_Marking#4]
When running the script with a map like the one shown below, the python script crashes. The robot is required to turn twice at the beginning. 

```
 --- --- --- --- --- --- --- --- --- 
| <                                      
 --- 
```                                
...

Thanks``

**Comment by ljden** [comment]
pretty sure the tutors clarified that this scenario won't occur

**Comment by AlyVirani** [comment]
> won't occur

Sweet! Thanks

**Comment by DanSpicyTaco** [comment]
Can confirm - robot will initially face an open side.
